version: '3.8'

services:
  db:
    container_name: db
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  proxy:
    ports:
      - "8080:8080"
    build:
      dockerfile: Dockerfile
      context: ./proxy
    depends_on:
      - db

  web:
    ports:
      - "8000:8000"
    build:
      dockerfile: Dockerfile
      context: ./webApi
    depends_on:
      - db
